package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
)

// MetadataGetNodeDdl is the resolver for the metadataGetNodeDDL field.
func (r *queryResolver) MetadataGetNodeDdl(ctx context.Context, nodeID string, options any) (*string, error) {
	panic(fmt.Errorf("not implemented: MetadataGetNodeDdl - metadataGetNodeDDL"))
}

// MetadataGetNodeExtendedDdl is the resolver for the metadataGetNodeExtendedDDL field.
func (r *queryResolver) MetadataGetNodeExtendedDdl(ctx context.Context, nodeID string) (*string, error) {
	panic(fmt.Errorf("not implemented: MetadataGetNodeExtendedDdl - metadataGetNodeExtendedDDL"))
}
