package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/actiontech/dms/internal/pkg/cloudbeaver/model"
)

// SetUserConfigurationParameter is the resolver for the setUserConfigurationParameter field.
func (r *mutationResolver) SetUserConfigurationParameter(ctx context.Context, name string, value any) (bool, error) {
	panic(fmt.Errorf("not implemented: SetUserConfigurationParameter - setUserConfigurationParameter"))
}

// SetUserPreferences is the resolver for the setUserPreferences field.
func (r *mutationResolver) SetUserPreferences(ctx context.Context, preferences any) (*model.UserInfo, error) {
	panic(fmt.Errorf("not implemented: SetUserPreferences - setUserPreferences"))
}

// FederatedLogin is the resolver for the federatedLogin field.
func (r *mutationResolver) FederatedLogin(ctx context.Context, provider string, configuration *string, linkUser *bool, forceSessionsLogout *bool) (*model.FederatedAuthInfo, error) {
	panic(fmt.Errorf("not implemented: FederatedLogin - federatedLogin"))
}

// AuthLogin is the resolver for the authLogin field.
func (r *queryResolver) AuthLogin(ctx context.Context, provider string, configuration *string, credentials any, linkUser *bool, forceSessionsLogout *bool) (*model.AuthInfo, error) {
	panic(fmt.Errorf("not implemented: AuthLogin - authLogin"))
}

// FederatedAuthTaskResult is the resolver for the federatedAuthTaskResult field.
func (r *queryResolver) FederatedAuthTaskResult(ctx context.Context, taskID string) (*model.FederatedAuthResult, error) {
	panic(fmt.Errorf("not implemented: FederatedAuthTaskResult - federatedAuthTaskResult"))
}

// AuthUpdateStatus is the resolver for the authUpdateStatus field.
func (r *queryResolver) AuthUpdateStatus(ctx context.Context, authID string, linkUser *bool) (*model.AuthInfo, error) {
	panic(fmt.Errorf("not implemented: AuthUpdateStatus - authUpdateStatus"))
}

// AuthLogout is the resolver for the authLogout field.
func (r *queryResolver) AuthLogout(ctx context.Context, provider *string, configuration *string) (*bool, error) {
	panic(fmt.Errorf("not implemented: AuthLogout - authLogout"))
}

// AuthLogoutExtended is the resolver for the authLogoutExtended field.
func (r *queryResolver) AuthLogoutExtended(ctx context.Context, provider *string, configuration *string) (*model.LogoutInfo, error) {
	panic(fmt.Errorf("not implemented: AuthLogoutExtended - authLogoutExtended"))
}

// ActiveUser is the resolver for the activeUser field.
func (r *queryResolver) ActiveUser(ctx context.Context) (*model.UserInfo, error) {
	panic(fmt.Errorf("not implemented: ActiveUser - activeUser"))
}

// AuthProviders is the resolver for the authProviders field.
func (r *queryResolver) AuthProviders(ctx context.Context) ([]*model.AuthProviderInfo, error) {
	panic(fmt.Errorf("not implemented: AuthProviders - authProviders"))
}

// AuthChangeLocalPassword is the resolver for the authChangeLocalPassword field.
func (r *queryResolver) AuthChangeLocalPassword(ctx context.Context, oldPassword string, newPassword string) (bool, error) {
	panic(fmt.Errorf("not implemented: AuthChangeLocalPassword - authChangeLocalPassword"))
}

// ListUserProfileProperties is the resolver for the listUserProfileProperties field.
func (r *queryResolver) ListUserProfileProperties(ctx context.Context) ([]*model.ObjectPropertyInfo, error) {
	panic(fmt.Errorf("not implemented: ListUserProfileProperties - listUserProfileProperties"))
}
