package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/actiontech/dms/internal/pkg/cloudbeaver/model"
)

// DataTransferAvailableStreamProcessors is the resolver for the dataTransferAvailableStreamProcessors field.
func (r *queryResolver) DataTransferAvailableStreamProcessors(ctx context.Context) ([]*model.DataTransferProcessorInfo, error) {
	panic(fmt.Errorf("not implemented: DataTransferAvailableStreamProcessors - dataTransferAvailableStreamProcessors"))
}

// DataTransferAvailableImportStreamProcessors is the resolver for the dataTransferAvailableImportStreamProcessors field.
func (r *queryResolver) DataTransferAvailableImportStreamProcessors(ctx context.Context) ([]*model.DataTransferProcessorInfo, error) {
	panic(fmt.Errorf("not implemented: DataTransferAvailableImportStreamProcessors - dataTransferAvailableImportStreamProcessors"))
}

// DataTransferDefaultExportSettings is the resolver for the dataTransferDefaultExportSettings field.
func (r *queryResolver) DataTransferDefaultExportSettings(ctx context.Context) (*model.DataTransferDefaultExportSettings, error) {
	panic(fmt.Errorf("not implemented: DataTransferDefaultExportSettings - dataTransferDefaultExportSettings"))
}

// DataTransferExportDataFromContainer is the resolver for the dataTransferExportDataFromContainer field.
func (r *queryResolver) DataTransferExportDataFromContainer(ctx context.Context, projectID *string, connectionID string, containerNodePath string, parameters model.DataTransferParameters) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: DataTransferExportDataFromContainer - dataTransferExportDataFromContainer"))
}

// DataTransferExportDataFromResults is the resolver for the dataTransferExportDataFromResults field.
func (r *queryResolver) DataTransferExportDataFromResults(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, parameters model.DataTransferParameters) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: DataTransferExportDataFromResults - dataTransferExportDataFromResults"))
}

// DataTransferRemoveDataFile is the resolver for the dataTransferRemoveDataFile field.
func (r *queryResolver) DataTransferRemoveDataFile(ctx context.Context, dataFileID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DataTransferRemoveDataFile - dataTransferRemoveDataFile"))
}
