package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/actiontech/dms/internal/pkg/cloudbeaver/model"
)

// SQLContextCreate is the resolver for the sqlContextCreate field.
func (r *mutationResolver) SQLContextCreate(ctx context.Context, projectID *string, connectionID string, defaultCatalog *string, defaultSchema *string) (*model.SQLContextInfo, error) {
	panic(fmt.Errorf("not implemented: SQLContextCreate - sqlContextCreate"))
}

// SQLContextSetDefaults is the resolver for the sqlContextSetDefaults field.
func (r *mutationResolver) SQLContextSetDefaults(ctx context.Context, projectID *string, connectionID string, contextID string, defaultCatalog *string, defaultSchema *string) (bool, error) {
	panic(fmt.Errorf("not implemented: SQLContextSetDefaults - sqlContextSetDefaults"))
}

// SQLContextDestroy is the resolver for the sqlContextDestroy field.
func (r *mutationResolver) SQLContextDestroy(ctx context.Context, projectID *string, connectionID string, contextID string) (bool, error) {
	panic(fmt.Errorf("not implemented: SQLContextDestroy - sqlContextDestroy"))
}

// AsyncSQLExecuteQuery is the resolver for the asyncSqlExecuteQuery field.
func (r *mutationResolver) AsyncSQLExecuteQuery(ctx context.Context, projectID *string, connectionID string, contextID string, sql string, resultID *string, filter *model.SQLDataFilter, dataFormat *model.ResultDataFormat, readLogs *bool) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLExecuteQuery - asyncSqlExecuteQuery"))
}

// AsyncReadDataFromContainer is the resolver for the asyncReadDataFromContainer field.
func (r *mutationResolver) AsyncReadDataFromContainer(ctx context.Context, projectID *string, connectionID string, contextID string, containerNodePath string, resultID *string, filter *model.SQLDataFilter, dataFormat *model.ResultDataFormat) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncReadDataFromContainer - asyncReadDataFromContainer"))
}

// GetTransactionLogInfo is the resolver for the getTransactionLogInfo field.
func (r *mutationResolver) GetTransactionLogInfo(ctx context.Context, projectID string, connectionID string, contextID string) (*model.TransactionLogInfos, error) {
	panic(fmt.Errorf("not implemented: GetTransactionLogInfo - getTransactionLogInfo"))
}

// SQLResultClose is the resolver for the sqlResultClose field.
func (r *mutationResolver) SQLResultClose(ctx context.Context, projectID *string, connectionID string, contextID string, resultID string) (bool, error) {
	panic(fmt.Errorf("not implemented: SQLResultClose - sqlResultClose"))
}

// AsyncUpdateResultsDataBatch is the resolver for the asyncUpdateResultsDataBatch field.
func (r *mutationResolver) AsyncUpdateResultsDataBatch(ctx context.Context, projectID string, connectionID string, contextID string, resultsID string, updatedRows []*model.SQLResultRow, deletedRows []*model.SQLResultRow, addedRows []*model.SQLResultRow) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncUpdateResultsDataBatch - asyncUpdateResultsDataBatch"))
}

// UpdateResultsDataBatch is the resolver for the updateResultsDataBatch field.
func (r *mutationResolver) UpdateResultsDataBatch(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, updatedRows []*model.SQLResultRow, deletedRows []*model.SQLResultRow, addedRows []*model.SQLResultRow) (*model.SQLExecuteInfo, error) {
	panic(fmt.Errorf("not implemented: UpdateResultsDataBatch - updateResultsDataBatch"))
}

// UpdateResultsDataBatchScript is the resolver for the updateResultsDataBatchScript field.
func (r *mutationResolver) UpdateResultsDataBatchScript(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, updatedRows []*model.SQLResultRow, deletedRows []*model.SQLResultRow, addedRows []*model.SQLResultRow) (string, error) {
	panic(fmt.Errorf("not implemented: UpdateResultsDataBatchScript - updateResultsDataBatchScript"))
}

// ReadLobValue is the resolver for the readLobValue field.
func (r *mutationResolver) ReadLobValue(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, lobColumnIndex int, row []*model.SQLResultRow) (string, error) {
	panic(fmt.Errorf("not implemented: ReadLobValue - readLobValue"))
}

// SQLReadLobValue is the resolver for the sqlReadLobValue field.
func (r *mutationResolver) SQLReadLobValue(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, lobColumnIndex int, row model.SQLResultRow) (string, error) {
	panic(fmt.Errorf("not implemented: SQLReadLobValue - sqlReadLobValue"))
}

// SQLReadStringValue is the resolver for the sqlReadStringValue field.
func (r *mutationResolver) SQLReadStringValue(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, columnIndex int, row model.SQLResultRow) (string, error) {
	panic(fmt.Errorf("not implemented: SQLReadStringValue - sqlReadStringValue"))
}

// AsyncSQLExecuteResults is the resolver for the asyncSqlExecuteResults field.
func (r *mutationResolver) AsyncSQLExecuteResults(ctx context.Context, taskID string) (*model.SQLExecuteInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLExecuteResults - asyncSqlExecuteResults"))
}

// AsyncSQLExplainExecutionPlan is the resolver for the asyncSqlExplainExecutionPlan field.
func (r *mutationResolver) AsyncSQLExplainExecutionPlan(ctx context.Context, projectID *string, connectionID string, contextID string, query string, configuration any) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLExplainExecutionPlan - asyncSqlExplainExecutionPlan"))
}

// AsyncSQLExplainExecutionPlanResult is the resolver for the asyncSqlExplainExecutionPlanResult field.
func (r *mutationResolver) AsyncSQLExplainExecutionPlanResult(ctx context.Context, taskID string) (*model.SQLExecutionPlan, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLExplainExecutionPlanResult - asyncSqlExplainExecutionPlanResult"))
}

// AsyncSQLRowDataCount is the resolver for the asyncSqlRowDataCount field.
func (r *mutationResolver) AsyncSQLRowDataCount(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLRowDataCount - asyncSqlRowDataCount"))
}

// AsyncSQLRowDataCountResult is the resolver for the asyncSqlRowDataCountResult field.
func (r *mutationResolver) AsyncSQLRowDataCountResult(ctx context.Context, taskID string) (int, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLRowDataCountResult - asyncSqlRowDataCountResult"))
}

// SQLGetDynamicTrace is the resolver for the sqlGetDynamicTrace field.
func (r *mutationResolver) SQLGetDynamicTrace(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string) ([]*model.DynamicTraceProperty, error) {
	panic(fmt.Errorf("not implemented: SQLGetDynamicTrace - sqlGetDynamicTrace"))
}

// AsyncSQLSetAutoCommit is the resolver for the asyncSqlSetAutoCommit field.
func (r *mutationResolver) AsyncSQLSetAutoCommit(ctx context.Context, projectID string, connectionID string, contextID string, autoCommit bool) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLSetAutoCommit - asyncSqlSetAutoCommit"))
}

// AsyncSQLCommitTransaction is the resolver for the asyncSqlCommitTransaction field.
func (r *mutationResolver) AsyncSQLCommitTransaction(ctx context.Context, projectID string, connectionID string, contextID string) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLCommitTransaction - asyncSqlCommitTransaction"))
}

// AsyncSQLRollbackTransaction is the resolver for the asyncSqlRollbackTransaction field.
func (r *mutationResolver) AsyncSQLRollbackTransaction(ctx context.Context, projectID string, connectionID string, contextID string) (*model.AsyncTaskInfo, error) {
	panic(fmt.Errorf("not implemented: AsyncSQLRollbackTransaction - asyncSqlRollbackTransaction"))
}

// SQLDialectInfo is the resolver for the sqlDialectInfo field.
func (r *queryResolver) SQLDialectInfo(ctx context.Context, projectID *string, connectionID string) (*model.SQLDialectInfo, error) {
	panic(fmt.Errorf("not implemented: SQLDialectInfo - sqlDialectInfo"))
}

// SQLListContexts is the resolver for the sqlListContexts field.
func (r *queryResolver) SQLListContexts(ctx context.Context, projectID *string, connectionID *string, contextID *string) ([]*model.SQLContextInfo, error) {
	panic(fmt.Errorf("not implemented: SQLListContexts - sqlListContexts"))
}

// SQLCompletionProposals is the resolver for the sqlCompletionProposals field.
func (r *queryResolver) SQLCompletionProposals(ctx context.Context, projectID *string, connectionID string, contextID string, query string, position int, maxResults *int, simpleMode *bool) ([]*model.SQLCompletionProposal, error) {
	panic(fmt.Errorf("not implemented: SQLCompletionProposals - sqlCompletionProposals"))
}

// SQLFormatQuery is the resolver for the sqlFormatQuery field.
func (r *queryResolver) SQLFormatQuery(ctx context.Context, projectID *string, connectionID string, contextID string, query string) (string, error) {
	panic(fmt.Errorf("not implemented: SQLFormatQuery - sqlFormatQuery"))
}

// SQLSupportedOperations is the resolver for the sqlSupportedOperations field.
func (r *queryResolver) SQLSupportedOperations(ctx context.Context, projectID *string, connectionID string, contextID string, resultsID string, attributeIndex int) ([]*model.DataTypeLogicalOperation, error) {
	panic(fmt.Errorf("not implemented: SQLSupportedOperations - sqlSupportedOperations"))
}

// SQLEntityQueryGenerators is the resolver for the sqlEntityQueryGenerators field.
func (r *queryResolver) SQLEntityQueryGenerators(ctx context.Context, nodePathList []string) ([]*model.SQLQueryGenerator, error) {
	panic(fmt.Errorf("not implemented: SQLEntityQueryGenerators - sqlEntityQueryGenerators"))
}

// SQLGenerateEntityQuery is the resolver for the sqlGenerateEntityQuery field.
func (r *queryResolver) SQLGenerateEntityQuery(ctx context.Context, generatorID string, options any, nodePathList []string) (string, error) {
	panic(fmt.Errorf("not implemented: SQLGenerateEntityQuery - sqlGenerateEntityQuery"))
}

// SQLParseScript is the resolver for the sqlParseScript field.
func (r *queryResolver) SQLParseScript(ctx context.Context, projectID *string, connectionID string, script string) (*model.SQLScriptInfo, error) {
	panic(fmt.Errorf("not implemented: SQLParseScript - sqlParseScript"))
}

// SQLParseQuery is the resolver for the sqlParseQuery field.
func (r *queryResolver) SQLParseQuery(ctx context.Context, projectID *string, connectionID string, script string, position int) (*model.SQLScriptQuery, error) {
	panic(fmt.Errorf("not implemented: SQLParseQuery - sqlParseQuery"))
}

// SQLGenerateGroupingQuery is the resolver for the sqlGenerateGroupingQuery field.
func (r *queryResolver) SQLGenerateGroupingQuery(ctx context.Context, projectID *string, contextID string, connectionID string, resultsID string, columnNames []string, functions []string, showDuplicatesOnly *bool) (string, error) {
	panic(fmt.Errorf("not implemented: SQLGenerateGroupingQuery - sqlGenerateGroupingQuery"))
}
