package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/actiontech/dms/internal/pkg/cloudbeaver/model"
)

// AdminUpdateProductConfiguration is the resolver for the adminUpdateProductConfiguration field.
func (r *mutationResolver) AdminUpdateProductConfiguration(ctx context.Context, configuration any) (bool, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateProductConfiguration - adminUpdateProductConfiguration"))
}

// AdminUserInfo is the resolver for the adminUserInfo field.
func (r *queryResolver) AdminUserInfo(ctx context.Context, userID string) (*model.AdminUserInfo, error) {
	panic(fmt.Errorf("not implemented: AdminUserInfo - adminUserInfo"))
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, page model.PageInput, filter model.AdminUserFilterInput) ([]*model.AdminUserInfo, error) {
	panic(fmt.Errorf("not implemented: ListUsers - listUsers"))
}

// ListTeams is the resolver for the listTeams field.
func (r *queryResolver) ListTeams(ctx context.Context, teamID *string) ([]*model.AdminTeamInfo, error) {
	panic(fmt.Errorf("not implemented: ListTeams - listTeams"))
}

// ListPermissions is the resolver for the listPermissions field.
func (r *queryResolver) ListPermissions(ctx context.Context) ([]*model.AdminPermissionInfo, error) {
	panic(fmt.Errorf("not implemented: ListPermissions - listPermissions"))
}

// ListAuthRoles is the resolver for the listAuthRoles field.
func (r *queryResolver) ListAuthRoles(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: ListAuthRoles - listAuthRoles"))
}

// ListTeamRoles is the resolver for the listTeamRoles field.
func (r *queryResolver) ListTeamRoles(ctx context.Context) ([]string, error) {
	panic(fmt.Errorf("not implemented: ListTeamRoles - listTeamRoles"))
}

// ListTeamMetaParameters is the resolver for the listTeamMetaParameters field.
func (r *queryResolver) ListTeamMetaParameters(ctx context.Context) ([]*model.ObjectPropertyInfo, error) {
	panic(fmt.Errorf("not implemented: ListTeamMetaParameters - listTeamMetaParameters"))
}

// CreateUser is the resolver for the createUser field.
func (r *queryResolver) CreateUser(ctx context.Context, userID string, enabled bool, authRole *string) (*model.AdminUserInfo, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *queryResolver) DeleteUser(ctx context.Context, userID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// CreateTeam is the resolver for the createTeam field.
func (r *queryResolver) CreateTeam(ctx context.Context, teamID string, teamName *string, description *string) (*model.AdminTeamInfo, error) {
	panic(fmt.Errorf("not implemented: CreateTeam - createTeam"))
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *queryResolver) UpdateTeam(ctx context.Context, teamID string, teamName *string, description *string) (*model.AdminTeamInfo, error) {
	panic(fmt.Errorf("not implemented: UpdateTeam - updateTeam"))
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *queryResolver) DeleteTeam(ctx context.Context, teamID string, force *bool) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTeam - deleteTeam"))
}

// GrantUserTeam is the resolver for the grantUserTeam field.
func (r *queryResolver) GrantUserTeam(ctx context.Context, userID string, teamID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: GrantUserTeam - grantUserTeam"))
}

// RevokeUserTeam is the resolver for the revokeUserTeam field.
func (r *queryResolver) RevokeUserTeam(ctx context.Context, userID string, teamID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: RevokeUserTeam - revokeUserTeam"))
}

// SetSubjectPermissions is the resolver for the setSubjectPermissions field.
func (r *queryResolver) SetSubjectPermissions(ctx context.Context, subjectID string, permissions []string) ([]*model.AdminPermissionInfo, error) {
	panic(fmt.Errorf("not implemented: SetSubjectPermissions - setSubjectPermissions"))
}

// SetUserCredentials is the resolver for the setUserCredentials field.
func (r *queryResolver) SetUserCredentials(ctx context.Context, userID string, providerID string, credentials any) (*bool, error) {
	panic(fmt.Errorf("not implemented: SetUserCredentials - setUserCredentials"))
}

// DeleteUserCredentials is the resolver for the deleteUserCredentials field.
func (r *queryResolver) DeleteUserCredentials(ctx context.Context, userID string, providerID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUserCredentials - deleteUserCredentials"))
}

// EnableUser is the resolver for the enableUser field.
func (r *queryResolver) EnableUser(ctx context.Context, userID string, enabled bool) (*bool, error) {
	panic(fmt.Errorf("not implemented: EnableUser - enableUser"))
}

// SetUserAuthRole is the resolver for the setUserAuthRole field.
func (r *queryResolver) SetUserAuthRole(ctx context.Context, userID string, authRole *string) (*bool, error) {
	panic(fmt.Errorf("not implemented: SetUserAuthRole - setUserAuthRole"))
}

// SetUserTeamRole is the resolver for the setUserTeamRole field.
func (r *queryResolver) SetUserTeamRole(ctx context.Context, userID string, teamID string, teamRole *string) (*bool, error) {
	panic(fmt.Errorf("not implemented: SetUserTeamRole - setUserTeamRole"))
}

// SearchConnections is the resolver for the searchConnections field.
func (r *queryResolver) SearchConnections(ctx context.Context, hostNames []string) ([]*model.AdminConnectionSearchInfo, error) {
	panic(fmt.Errorf("not implemented: SearchConnections - searchConnections"))
}

// GetConnectionSubjectAccess is the resolver for the getConnectionSubjectAccess field.
func (r *queryResolver) GetConnectionSubjectAccess(ctx context.Context, projectID string, connectionID *string) ([]*model.AdminConnectionGrantInfo, error) {
	panic(fmt.Errorf("not implemented: GetConnectionSubjectAccess - getConnectionSubjectAccess"))
}

// SetConnectionSubjectAccess is the resolver for the setConnectionSubjectAccess field.
func (r *queryResolver) SetConnectionSubjectAccess(ctx context.Context, projectID string, connectionID string, subjects []string) (*bool, error) {
	panic(fmt.Errorf("not implemented: SetConnectionSubjectAccess - setConnectionSubjectAccess"))
}

// AddConnectionsAccess is the resolver for the addConnectionsAccess field.
func (r *queryResolver) AddConnectionsAccess(ctx context.Context, projectID string, connectionIds []string, subjects []string) (*bool, error) {
	panic(fmt.Errorf("not implemented: AddConnectionsAccess - addConnectionsAccess"))
}

// DeleteConnectionsAccess is the resolver for the deleteConnectionsAccess field.
func (r *queryResolver) DeleteConnectionsAccess(ctx context.Context, projectID string, connectionIds []string, subjects []string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteConnectionsAccess - deleteConnectionsAccess"))
}

// GetSubjectConnectionAccess is the resolver for the getSubjectConnectionAccess field.
func (r *queryResolver) GetSubjectConnectionAccess(ctx context.Context, subjectID string) ([]*model.AdminConnectionGrantInfo, error) {
	panic(fmt.Errorf("not implemented: GetSubjectConnectionAccess - getSubjectConnectionAccess"))
}

// SetSubjectConnectionAccess is the resolver for the setSubjectConnectionAccess field.
func (r *queryResolver) SetSubjectConnectionAccess(ctx context.Context, subjectID string, connections []string) (*bool, error) {
	panic(fmt.Errorf("not implemented: SetSubjectConnectionAccess - setSubjectConnectionAccess"))
}

// ListFeatureSets is the resolver for the listFeatureSets field.
func (r *queryResolver) ListFeatureSets(ctx context.Context) ([]*model.WebFeatureSet, error) {
	panic(fmt.Errorf("not implemented: ListFeatureSets - listFeatureSets"))
}

// ListAuthProviderConfigurationParameters is the resolver for the listAuthProviderConfigurationParameters field.
func (r *queryResolver) ListAuthProviderConfigurationParameters(ctx context.Context, providerID string) ([]*model.ObjectPropertyInfo, error) {
	panic(fmt.Errorf("not implemented: ListAuthProviderConfigurationParameters - listAuthProviderConfigurationParameters"))
}

// ListAuthProviderConfigurations is the resolver for the listAuthProviderConfigurations field.
func (r *queryResolver) ListAuthProviderConfigurations(ctx context.Context, providerID *string) ([]*model.AdminAuthProviderConfiguration, error) {
	panic(fmt.Errorf("not implemented: ListAuthProviderConfigurations - listAuthProviderConfigurations"))
}

// SaveAuthProviderConfiguration is the resolver for the saveAuthProviderConfiguration field.
func (r *queryResolver) SaveAuthProviderConfiguration(ctx context.Context, providerID string, id string, displayName *string, disabled *bool, iconURL *string, description *string, parameters any) (*model.AdminAuthProviderConfiguration, error) {
	panic(fmt.Errorf("not implemented: SaveAuthProviderConfiguration - saveAuthProviderConfiguration"))
}

// DeleteAuthProviderConfiguration is the resolver for the deleteAuthProviderConfiguration field.
func (r *queryResolver) DeleteAuthProviderConfiguration(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAuthProviderConfiguration - deleteAuthProviderConfiguration"))
}

// SaveUserMetaParameter is the resolver for the saveUserMetaParameter field.
func (r *queryResolver) SaveUserMetaParameter(ctx context.Context, id string, displayName string, description *string, required bool) (*model.ObjectPropertyInfo, error) {
	panic(fmt.Errorf("not implemented: SaveUserMetaParameter - saveUserMetaParameter"))
}

// DeleteUserMetaParameter is the resolver for the deleteUserMetaParameter field.
func (r *queryResolver) DeleteUserMetaParameter(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUserMetaParameter - deleteUserMetaParameter"))
}

// SetUserMetaParameterValues is the resolver for the setUserMetaParameterValues field.
func (r *queryResolver) SetUserMetaParameterValues(ctx context.Context, userID string, parameters any) (bool, error) {
	panic(fmt.Errorf("not implemented: SetUserMetaParameterValues - setUserMetaParameterValues"))
}

// SetTeamMetaParameterValues is the resolver for the setTeamMetaParameterValues field.
func (r *queryResolver) SetTeamMetaParameterValues(ctx context.Context, teamID string, parameters any) (bool, error) {
	panic(fmt.Errorf("not implemented: SetTeamMetaParameterValues - setTeamMetaParameterValues"))
}

// ConfigureServer is the resolver for the configureServer field.
func (r *queryResolver) ConfigureServer(ctx context.Context, configuration model.ServerConfigInput) (bool, error) {
	panic(fmt.Errorf("not implemented: ConfigureServer - configureServer"))
}

// SetDefaultNavigatorSettings is the resolver for the setDefaultNavigatorSettings field.
func (r *queryResolver) SetDefaultNavigatorSettings(ctx context.Context, settings model.NavigatorSettingsInput) (bool, error) {
	panic(fmt.Errorf("not implemented: SetDefaultNavigatorSettings - setDefaultNavigatorSettings"))
}
