package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/actiontech/dms/internal/pkg/cloudbeaver/model"
)

// RmCreateResource is the resolver for the rmCreateResource field.
func (r *mutationResolver) RmCreateResource(ctx context.Context, projectID string, resourcePath string, isFolder bool) (string, error) {
	panic(fmt.Errorf("not implemented: RmCreateResource - rmCreateResource"))
}

// RmMoveResource is the resolver for the rmMoveResource field.
func (r *mutationResolver) RmMoveResource(ctx context.Context, projectID string, oldResourcePath string, newResourcePath *string) (string, error) {
	panic(fmt.Errorf("not implemented: RmMoveResource - rmMoveResource"))
}

// RmDeleteResource is the resolver for the rmDeleteResource field.
func (r *mutationResolver) RmDeleteResource(ctx context.Context, projectID string, resourcePath string, recursive bool) (*bool, error) {
	panic(fmt.Errorf("not implemented: RmDeleteResource - rmDeleteResource"))
}

// RmWriteResourceStringContent is the resolver for the rmWriteResourceStringContent field.
func (r *mutationResolver) RmWriteResourceStringContent(ctx context.Context, projectID string, resourcePath string, data string, forceOverwrite bool) (string, error) {
	panic(fmt.Errorf("not implemented: RmWriteResourceStringContent - rmWriteResourceStringContent"))
}

// RmCreateProject is the resolver for the rmCreateProject field.
func (r *mutationResolver) RmCreateProject(ctx context.Context, projectID *string, projectName string, description *string) (*model.RMProject, error) {
	panic(fmt.Errorf("not implemented: RmCreateProject - rmCreateProject"))
}

// RmDeleteProject is the resolver for the rmDeleteProject field.
func (r *mutationResolver) RmDeleteProject(ctx context.Context, projectID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RmDeleteProject - rmDeleteProject"))
}

// RmSetProjectPermissions is the resolver for the rmSetProjectPermissions field.
func (r *mutationResolver) RmSetProjectPermissions(ctx context.Context, projectID string, permissions []*model.RMSubjectProjectPermissions) (bool, error) {
	panic(fmt.Errorf("not implemented: RmSetProjectPermissions - rmSetProjectPermissions"))
}

// RmSetSubjectProjectPermissions is the resolver for the rmSetSubjectProjectPermissions field.
func (r *mutationResolver) RmSetSubjectProjectPermissions(ctx context.Context, subjectID string, permissions []*model.RMProjectPermissions) (bool, error) {
	panic(fmt.Errorf("not implemented: RmSetSubjectProjectPermissions - rmSetSubjectProjectPermissions"))
}

// RmAddProjectsPermissions is the resolver for the rmAddProjectsPermissions field.
func (r *mutationResolver) RmAddProjectsPermissions(ctx context.Context, projectIds []string, subjectIds []string, permissions []string) (*bool, error) {
	panic(fmt.Errorf("not implemented: RmAddProjectsPermissions - rmAddProjectsPermissions"))
}

// RmDeleteProjectsPermissions is the resolver for the rmDeleteProjectsPermissions field.
func (r *mutationResolver) RmDeleteProjectsPermissions(ctx context.Context, projectIds []string, subjectIds []string, permissions []string) (*bool, error) {
	panic(fmt.Errorf("not implemented: RmDeleteProjectsPermissions - rmDeleteProjectsPermissions"))
}

// RmSetResourceProperty is the resolver for the rmSetResourceProperty field.
func (r *mutationResolver) RmSetResourceProperty(ctx context.Context, projectID string, resourcePath string, name string, value *string) (bool, error) {
	panic(fmt.Errorf("not implemented: RmSetResourceProperty - rmSetResourceProperty"))
}

// RmListProjects is the resolver for the rmListProjects field.
func (r *queryResolver) RmListProjects(ctx context.Context) ([]*model.RMProject, error) {
	panic(fmt.Errorf("not implemented: RmListProjects - rmListProjects"))
}

// RmListSharedProjects is the resolver for the rmListSharedProjects field.
func (r *queryResolver) RmListSharedProjects(ctx context.Context) ([]*model.RMProject, error) {
	panic(fmt.Errorf("not implemented: RmListSharedProjects - rmListSharedProjects"))
}

// RmProject is the resolver for the rmProject field.
func (r *queryResolver) RmProject(ctx context.Context, projectID string) (*model.RMProject, error) {
	panic(fmt.Errorf("not implemented: RmProject - rmProject"))
}

// RmListProjectPermissions is the resolver for the rmListProjectPermissions field.
func (r *queryResolver) RmListProjectPermissions(ctx context.Context) ([]*model.AdminPermissionInfo, error) {
	panic(fmt.Errorf("not implemented: RmListProjectPermissions - rmListProjectPermissions"))
}

// RmListProjectGrantedPermissions is the resolver for the rmListProjectGrantedPermissions field.
func (r *queryResolver) RmListProjectGrantedPermissions(ctx context.Context, projectID string) ([]*model.AdminObjectGrantInfo, error) {
	panic(fmt.Errorf("not implemented: RmListProjectGrantedPermissions - rmListProjectGrantedPermissions"))
}

// RmListSubjectProjectsPermissionGrants is the resolver for the rmListSubjectProjectsPermissionGrants field.
func (r *queryResolver) RmListSubjectProjectsPermissionGrants(ctx context.Context, subjectID string) ([]*model.AdminObjectGrantInfo, error) {
	panic(fmt.Errorf("not implemented: RmListSubjectProjectsPermissionGrants - rmListSubjectProjectsPermissionGrants"))
}

// RmListResources is the resolver for the rmListResources field.
func (r *queryResolver) RmListResources(ctx context.Context, projectID string, folder *string, nameMask *string, readProperties *bool, readHistory *bool) ([]*model.RMResource, error) {
	panic(fmt.Errorf("not implemented: RmListResources - rmListResources"))
}

// RmReadResourceAsString is the resolver for the rmReadResourceAsString field.
func (r *queryResolver) RmReadResourceAsString(ctx context.Context, projectID string, resourcePath string) (string, error) {
	panic(fmt.Errorf("not implemented: RmReadResourceAsString - rmReadResourceAsString"))
}
