// Code generated by gencli for actiontech dms. DO NOT EDIT
package biz

type DBServiceField string

type DMSConfigField string

type LDAPConfigurationField string

type MemberField string

type MemberRoleOpRangeField string

type ModelField string

type NamespaceField string

type Oauth2ConfigurationField string

type OpPermissionField string

type PluginField string

type ProxyTargetField string

type RoleField string

type UserField string

type UserGroupField string

const (
	DBServiceFieldUID               DBServiceField = "uid"
	DBServiceFieldName              DBServiceField = "name"
	DBServiceFieldDBType            DBServiceField = "db_type"
	DBServiceFieldHost              DBServiceField = "db_host"
	DBServiceFieldPort              DBServiceField = "db_port"
	DBServiceFieldUser              DBServiceField = "db_user"
	DBServiceFieldPassword          DBServiceField = "db_password"
	DBServiceFieldDesc              DBServiceField = "desc"
	DBServiceFieldBusiness          DBServiceField = "business"
	DBServiceFieldAdditionalParams  DBServiceField = "additionalparams"
	DBServiceFieldSource            DBServiceField = "source"
	DBServiceFieldNamespaceUID      DBServiceField = "namespace_uid"
	DBServiceFieldMaintenancePeriod DBServiceField = "maintenanceperiod"
	DBServiceFieldExtraParameters   DBServiceField = "extraparameters"
)

const (
	DMSConfigFieldUID                   DMSConfigField = "uid"
	DMSConfigFieldNeedInitOpPermissions DMSConfigField = "need_init_op_permissions"
	DMSConfigFieldNeedInitUsers         DMSConfigField = "need_init_users"
	DMSConfigFieldNeedInitRoles         DMSConfigField = "need_init_roles"
	DMSConfigFieldNeedInitNamespaces    DMSConfigField = "need_init_namespaces"
)

const (
	LDAPConfigurationFieldUID                   LDAPConfigurationField = "uid"
	LDAPConfigurationFieldEnable                LDAPConfigurationField = "enable"
	LDAPConfigurationFieldEnableSSL             LDAPConfigurationField = "enablessl"
	LDAPConfigurationFieldHost                  LDAPConfigurationField = "host"
	LDAPConfigurationFieldPort                  LDAPConfigurationField = "port"
	LDAPConfigurationFieldConnectDn             LDAPConfigurationField = "connectdn"
	LDAPConfigurationFieldConnectSecretPassword LDAPConfigurationField = "connectsecretpassword"
	LDAPConfigurationFieldBaseDn                LDAPConfigurationField = "basedn"
	LDAPConfigurationFieldUserNameRdnKey        LDAPConfigurationField = "usernamerdnkey"
	LDAPConfigurationFieldUserEmailRdnKey       LDAPConfigurationField = "useremailrdnkey"
)

const (
	MemberFieldUID              MemberField = "uid"
	MemberFieldUserUID          MemberField = "user_uid"
	MemberFieldNamespaceUID     MemberField = "namespace_uid"
	MemberFieldRoleWithOpRanges MemberField = "rolewithopranges"
)

const (
	MemberRoleOpRangeFieldMemberUID   MemberRoleOpRangeField = "member_uid"
	MemberRoleOpRangeFieldRoleUID     MemberRoleOpRangeField = "role_uid"
	MemberRoleOpRangeFieldOpRangeType MemberRoleOpRangeField = "op_range_type"
	MemberRoleOpRangeFieldRangeUIDs   MemberRoleOpRangeField = "range_uids"
)

const (
	ModelFieldUID ModelField = "uid"
)

const (
	NamespaceFieldUID           NamespaceField = "uid"
	NamespaceFieldName          NamespaceField = "name"
	NamespaceFieldDesc          NamespaceField = "desc"
	NamespaceFieldCreateUserUID NamespaceField = "create_user_uid"
	NamespaceFieldStatus        NamespaceField = "status"
)

const (
	Oauth2ConfigurationFieldUID             Oauth2ConfigurationField = "uid"
	Oauth2ConfigurationFieldEnableOauth2    Oauth2ConfigurationField = "enable_oauth2"
	Oauth2ConfigurationFieldClientID        Oauth2ConfigurationField = "client_id"
	Oauth2ConfigurationFieldClientKey       Oauth2ConfigurationField = "clientkey"
	Oauth2ConfigurationFieldClientSecret    Oauth2ConfigurationField = "clientsecret"
	Oauth2ConfigurationFieldClientHost      Oauth2ConfigurationField = "client_host"
	Oauth2ConfigurationFieldServerAuthUrl   Oauth2ConfigurationField = "server_auth_url"
	Oauth2ConfigurationFieldServerTokenUrl  Oauth2ConfigurationField = "server_token_url"
	Oauth2ConfigurationFieldServerUserIdUrl Oauth2ConfigurationField = "server_user_id_url"
	Oauth2ConfigurationFieldScopes          Oauth2ConfigurationField = "scopes"
	Oauth2ConfigurationFieldAccessTokenTag  Oauth2ConfigurationField = "access_token_tag"
	Oauth2ConfigurationFieldUserIdTag       Oauth2ConfigurationField = "user_id_tag"
	Oauth2ConfigurationFieldLoginTip        Oauth2ConfigurationField = "login_tip"
)

const (
	OpPermissionFieldUID       OpPermissionField = "uid"
	OpPermissionFieldName      OpPermissionField = "name"
	OpPermissionFieldDesc      OpPermissionField = "description"
	OpPermissionFieldRangeType OpPermissionField = "range_type"
)

const (
	PluginFieldName                         PluginField = "name"
	PluginFieldAddDBServicePreCheckUrl      PluginField = "add_db_service_pre_check_url"
	PluginFieldDelDBServicePreCheckUrl      PluginField = "del_db_service_pre_check_url"
	PluginFieldDelUserPreCheckUrl           PluginField = "del_user_pre_check_url"
	PluginFieldDelUserGroupPreCheckUrl      PluginField = "del_user_group_pre_check_url"
	PluginFieldOperateDataResourceHandleUrl PluginField = "operate_data_resource_handle_url"
)

const (
	ProxyTargetFieldName            ProxyTargetField = "name"
	ProxyTargetFieldUrl             ProxyTargetField = "url"
	ProxyTargetFieldProxyUrlPrefixs ProxyTargetField = "proxy_url_prefixs"
)

const (
	RoleFieldUID           RoleField = "uid"
	RoleFieldName          RoleField = "name"
	RoleFieldDesc          RoleField = "description"
	RoleFieldStat          RoleField = "stat"
	RoleFieldOpPermissions RoleField = "oppermissions"
)

const (
	UserFieldUID                    UserField = "uid"
	UserFieldName                   UserField = "name"
	UserFieldThirdPartyUserID       UserField = "third_party_user_id"
	UserFieldEmail                  UserField = "email"
	UserFieldPhone                  UserField = "phone"
	UserFieldWeChatID               UserField = "wechat_id"
	UserFieldPassword               UserField = "password"
	UserFieldUserAuthenticationType UserField = "user_authentication_type"
	UserFieldStat                   UserField = "stat"
	UserFieldLastLoginAt            UserField = "last_login_at"
	UserFieldDeletedAt              UserField = "delete_at"
	UserFieldUserGroups             UserField = "usergroups"
	UserFieldOpPermissions          UserField = "oppermissions"
)

const (
	UserGroupFieldUID   UserGroupField = "uid"
	UserGroupFieldName  UserGroupField = "name"
	UserGroupFieldDesc  UserGroupField = "description"
	UserGroupFieldStat  UserGroupField = "stat"
	UserGroupFieldUsers UserGroupField = "users"
)
